[build-system]
requires = ["setuptools>=60.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "my_library"
version = "0.1.0"
authors = [
  { name = "Your Name", email = "your_email@example.com" }
]
description = "A simple example library"